name: Create missing gauges for pools

on:
    workflow_dispatch:
        inputs:
            vote_end_timestamp:
                description: 'The timestamp of the end of the vote'
                require: true
env:
    UPDATER_WALLET: ${{ secrets.UPDATER_WALLET }}

jobs:
    initEpoch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install deps
              run: bun install --frozen-lockfile

            - name: Create missing gauges
              env:
                  VOTE_END_TIMESTAMP: ${{ github.event.inputs.vote_end_timestamp }}
              run: bun ts-node ./src/createGauges.ts
