name: Start new voting epoch

on:
    workflow_dispatch:
        inputs:
            beets_to_distribute:
                description: 'The amounts of BEETS to distribute'
                require: true
            vote_start_day:
                description: 'Start day of the vote (YYYY-MM-DD)'
                require: true
            vote_end_day:
                description: 'End day of the vote (YYYY-MM-DD)'
                require: true
            snapshot_block:
                description: 'Number of the block to snapshot'
                require: true

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PROPOSER_WALLET: ${{ secrets.PROPOSER_WALLET }}

jobs:
    initEpoch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install deps
              run: bun install --frozen-lockfile

            - name: Inititalize new epoch
              env:
                  BEETS_TO_DISTRIBUTE: ${{ github.event.inputs.beets_to_distribute }}
                  VOTE_START_DAY: ${{ github.event.inputs.vote_start_day }}
                  VOTE_END_DAY: ${{ github.event.inputs.vote_end_day }}
                  SNAPSHOT_BLOCK: ${{ github.event.inputs.snapshot_block }}
              run: bun ts-node ./src/inititalizeRound.ts

            - name: Create PR
              uses: peter-evans/create-pull-request@v5
              with:
                  commit-message: 'Inititalize new gauge epoch'
                  title: 'Inititalize new gauge epoch with ${{ github.event.inputs.beets_to_distribute }} BEETS'
                  assignees: franzns
                  branch: init-gauge-round
                  delete-branch: true
                  labels: 'Automated PR'
